[package]
name = "pbz"
version = "0.1.0"
edition = "2021"


[dependencies]
r2d2 = "0.8.10"
r2d2_postgres = "0.18.1"
postgres = { version = "0.19.9", features = ["with-chrono-0_4"] }
chrono = "0.4.38"
maud = "*"
