version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: PBZ2
    ports:
      - "5433:5432"  # Expose port 5432 to the host machine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: PBZ2
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
